package gui;

import file.CategoriesFile;
import file.IngredientsFile;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ListSelectionModel;
import model.FinalCategory;
import model.Ingredient;

/**
 *
 * @author Ayoze, Cristina
 */
public class AppForm extends javax.swing.JFrame {

    public IngredientsFile ingredientsFile = new IngredientsFile();
    public CategoriesFile categoriesFile = new CategoriesFile();
    
    
    private CardLayout cardLayout = new CardLayout();

    private ArrayList<Ingredient>ingredients = new ArrayList();
    private ArrayList<FinalCategory>categories = new ArrayList();
    
    private DefaultListModel ingredientsModel = new DefaultListModel();
    private DefaultListModel categoriesModel = new DefaultListModel();
    
    private void initIngredientsList(){
        for (Ingredient ingredient : ingredients) {
            ingredientsModel.addElement(ingredient);
        }
    }
    private void initCategoriesList(){
        for (FinalCategory category : categories) {
            categoriesModel.addElement(category);
        }
    }
    
    public AppForm() {
        initComponents();

        ingredientsList.setModel(ingredientsModel);
        categoriesList.setModel(categoriesModel);
        
        ingredientsList.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        categoriesList.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        ingredientsFile.loadFromFile(ingredients);
        categoriesFile.loadFromFile(categories);

        initIngredientsList();
        initCategoriesList();
        
        super.setSize(1280, 720);
        
        cardLayout = (CardLayout) jPanelCard.getLayout();
        jPanelCard.setLayout(cardLayout);
        
        //Botones del menu disponibles
        logInButton.setEnabled(true);
        createRecipeButton.setEnabled(false);
        createMenuButton.setEnabled(false);
        searchRecipeButton.setEnabled(false);
        rateRecipesButton.setEnabled(false);
        logOutButton.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPanel = new javax.swing.JSplitPane();
        jPanelCard = new javax.swing.JPanel();
        logInPanel = new javax.swing.JPanel();
        logInTittlePanel = new javax.swing.JPanel();
        logInTittlePanelLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        usernameTextArea = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        logInUserButton = new javax.swing.JButton();
        recipePanel = new javax.swing.JPanel();
        recipeTittlePanel = new javax.swing.JPanel();
        recipeTittlePanelLabel = new javax.swing.JLabel();
        nameRecipeLabel = new javax.swing.JLabel();
        recipeNameText = new javax.swing.JTextField();
        stepsLabel = new javax.swing.JLabel();
        stepsTextArea = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        cookTimeLabel = new javax.swing.JLabel();
        cookTimeText = new javax.swing.JTextField();
        priceLabel = new javax.swing.JLabel();
        priceText = new javax.swing.JTextField();
        ingredientsLabel = new javax.swing.JLabel();
        ingredientsScrollPane = new javax.swing.JScrollPane();
        ingredientsList = new javax.swing.JList<>();
        categoriesLabel = new javax.swing.JLabel();
        categoriesScrollPane = new javax.swing.JScrollPane();
        categoriesList = new javax.swing.JList<>();
        createRecipe = new javax.swing.JButton();
        resetRecipe = new javax.swing.JButton();
        buttonsPanel = new javax.swing.JPanel();
        logInButton = new javax.swing.JButton();
        logOutButton = new javax.swing.JButton();
        createRecipeButton = new javax.swing.JButton();
        createMenuButton = new javax.swing.JButton();
        searchRecipeButton = new javax.swing.JButton();
        rateRecipesButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 846));
        setMinimumSize(new java.awt.Dimension(1280, 846));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 848));

        jSplitPanel.setMaximumSize(new java.awt.Dimension(1280, 848));
        jSplitPanel.setMinimumSize(new java.awt.Dimension(1280, 848));
        jSplitPanel.setPreferredSize(new java.awt.Dimension(1280, 720));

        jPanelCard.setBackground(new java.awt.Color(203, 241, 245));
        jPanelCard.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanelCard.setMaximumSize(new java.awt.Dimension(1000, 846));
        jPanelCard.setMinimumSize(new java.awt.Dimension(1000, 846));
        jPanelCard.setPreferredSize(new java.awt.Dimension(1000, 846));
        jPanelCard.setLayout(new java.awt.CardLayout());

        logInPanel.setBackground(new java.awt.Color(57, 62, 70));
        logInPanel.setPreferredSize(new java.awt.Dimension(1006, 848));

        logInTittlePanel.setBackground(new java.awt.Color(78, 204, 163));

        logInTittlePanelLabel.setBackground(new java.awt.Color(78, 204, 163));
        logInTittlePanelLabel.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        logInTittlePanelLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logInTittlePanelLabel.setText("Log Into the app");

        javax.swing.GroupLayout logInTittlePanelLayout = new javax.swing.GroupLayout(logInTittlePanel);
        logInTittlePanel.setLayout(logInTittlePanelLayout);
        logInTittlePanelLayout.setHorizontalGroup(
            logInTittlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logInTittlePanelLayout.createSequentialGroup()
                .addComponent(logInTittlePanelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        logInTittlePanelLayout.setVerticalGroup(
            logInTittlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logInTittlePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(logInTittlePanelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        usernameLabel.setForeground(new java.awt.Color(238, 238, 238));
        usernameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usernameLabel.setText("USERNAME");

        usernameTextArea.setBackground(new java.awt.Color(35, 41, 49));
        usernameTextArea.setForeground(new java.awt.Color(238, 238, 238));

        passwordLabel.setForeground(new java.awt.Color(238, 238, 238));
        passwordLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        passwordLabel.setText("PASSWORD");

        passwordField.setBackground(new java.awt.Color(35, 41, 49));
        passwordField.setForeground(new java.awt.Color(238, 238, 238));

        logInUserButton.setBackground(new java.awt.Color(78, 204, 163));
        logInUserButton.setText("Log in");
        logInUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logInUserButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout logInPanelLayout = new javax.swing.GroupLayout(logInPanel);
        logInPanel.setLayout(logInPanelLayout);
        logInPanelLayout.setHorizontalGroup(
            logInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(usernameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(passwordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(logInPanelLayout.createSequentialGroup()
                .addComponent(logInTittlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(logInPanelLayout.createSequentialGroup()
                .addGap(419, 419, 419)
                .addGroup(logInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usernameTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logInPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(logInUserButton)
                .addGap(465, 465, 465))
        );
        logInPanelLayout.setVerticalGroup(
            logInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logInPanelLayout.createSequentialGroup()
                .addComponent(logInTittlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(usernameLabel)
                .addGap(18, 18, 18)
                .addComponent(usernameTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(passwordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(logInUserButton)
                .addContainerGap(515, Short.MAX_VALUE))
        );

        jPanelCard.add(logInPanel, "logInCard");

        recipePanel.setBackground(new java.awt.Color(57, 62, 70));
        recipePanel.setPreferredSize(new java.awt.Dimension(710, 848));

        recipeTittlePanel.setBackground(new java.awt.Color(78, 204, 163));

        recipeTittlePanelLabel.setBackground(new java.awt.Color(78, 204, 163));
        recipeTittlePanelLabel.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        recipeTittlePanelLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        recipeTittlePanelLabel.setText("Create your own recipe");

        javax.swing.GroupLayout recipeTittlePanelLayout = new javax.swing.GroupLayout(recipeTittlePanel);
        recipeTittlePanel.setLayout(recipeTittlePanelLayout);
        recipeTittlePanelLayout.setHorizontalGroup(
            recipeTittlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(recipeTittlePanelLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        recipeTittlePanelLayout.setVerticalGroup(
            recipeTittlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(recipeTittlePanelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        nameRecipeLabel.setBackground(new java.awt.Color(238, 238, 238));
        nameRecipeLabel.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        nameRecipeLabel.setForeground(new java.awt.Color(238, 238, 238));
        nameRecipeLabel.setText("Name:");

        recipeNameText.setBackground(new java.awt.Color(35, 41, 49));
        recipeNameText.setForeground(new java.awt.Color(238, 238, 238));

        stepsLabel.setBackground(new java.awt.Color(238, 238, 238));
        stepsLabel.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        stepsLabel.setForeground(new java.awt.Color(238, 238, 238));
        stepsLabel.setText("Steps:");

        jTextArea1.setBackground(new java.awt.Color(35, 41, 49));
        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(238, 238, 238));
        jTextArea1.setRows(5);
        stepsTextArea.setViewportView(jTextArea1);

        cookTimeLabel.setBackground(new java.awt.Color(238, 238, 238));
        cookTimeLabel.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        cookTimeLabel.setForeground(new java.awt.Color(238, 238, 238));
        cookTimeLabel.setText("Cook time:");

        cookTimeText.setBackground(new java.awt.Color(35, 41, 49));
        cookTimeText.setForeground(new java.awt.Color(238, 238, 238));

        priceLabel.setBackground(new java.awt.Color(238, 238, 238));
        priceLabel.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        priceLabel.setForeground(new java.awt.Color(238, 238, 238));
        priceLabel.setText("Price:");

        priceText.setBackground(new java.awt.Color(35, 41, 49));
        priceText.setForeground(new java.awt.Color(238, 238, 238));
        priceText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceTextActionPerformed(evt);
            }
        });

        ingredientsLabel.setBackground(new java.awt.Color(238, 238, 238));
        ingredientsLabel.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        ingredientsLabel.setForeground(new java.awt.Color(238, 238, 238));
        ingredientsLabel.setText("Ingredients:");

        ingredientsList.setBackground(new java.awt.Color(35, 41, 49));
        ingredientsList.setForeground(new java.awt.Color(238, 238, 238));
        ingredientsScrollPane.setViewportView(ingredientsList);

        categoriesLabel.setBackground(new java.awt.Color(238, 238, 238));
        categoriesLabel.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        categoriesLabel.setForeground(new java.awt.Color(238, 238, 238));
        categoriesLabel.setText("Categories:");

        categoriesList.setBackground(new java.awt.Color(35, 41, 49));
        categoriesList.setForeground(new java.awt.Color(238, 238, 238));
        categoriesList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        categoriesScrollPane.setViewportView(categoriesList);

        createRecipe.setBackground(new java.awt.Color(78, 204, 163));
        createRecipe.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        createRecipe.setForeground(new java.awt.Color(238, 238, 238));
        createRecipe.setText("Create");
        createRecipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createRecipeActionPerformed(evt);
            }
        });

        resetRecipe.setBackground(new java.awt.Color(78, 204, 163));
        resetRecipe.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        resetRecipe.setForeground(new java.awt.Color(238, 238, 238));
        resetRecipe.setText("Reset");

        javax.swing.GroupLayout recipePanelLayout = new javax.swing.GroupLayout(recipePanel);
        recipePanel.setLayout(recipePanelLayout);
        recipePanelLayout.setHorizontalGroup(
            recipePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(recipeTittlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(recipePanelLayout.createSequentialGroup()
                .addContainerGap(293, Short.MAX_VALUE)
                .addGroup(recipePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ingredientsLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cookTimeLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(stepsLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nameRecipeLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(priceLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(categoriesLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(recipePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(recipeNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stepsTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(recipePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, recipePanelLayout.createSequentialGroup()
                            .addComponent(createRecipe)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(resetRecipe))
                        .addComponent(categoriesScrollPane, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ingredientsScrollPane, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cookTimeText, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(priceText, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(294, Short.MAX_VALUE))
        );
        recipePanelLayout.setVerticalGroup(
            recipePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recipePanelLayout.createSequentialGroup()
                .addComponent(recipeTittlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(recipePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameRecipeLabel)
                    .addComponent(recipeNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(recipePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stepsTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stepsLabel))
                .addGap(18, 18, 18)
                .addGroup(recipePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cookTimeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cookTimeLabel))
                .addGap(18, 18, 18)
                .addGroup(recipePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceLabel)
                    .addComponent(priceText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(recipePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ingredientsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingredientsLabel))
                .addGap(18, 18, 18)
                .addGroup(recipePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(recipePanelLayout.createSequentialGroup()
                        .addComponent(categoriesScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(recipePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(resetRecipe)
                            .addComponent(createRecipe)))
                    .addComponent(categoriesLabel))
                .addContainerGap(96, Short.MAX_VALUE))
        );

        jPanelCard.add(recipePanel, "recipeCard");

        jSplitPanel.setLeftComponent(jPanelCard);

        buttonsPanel.setBackground(new java.awt.Color(238, 238, 238));

        logInButton.setBackground(new java.awt.Color(78, 204, 163));
        logInButton.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N
        logInButton.setForeground(new java.awt.Color(57, 62, 70));
        logInButton.setText("Log In");
        logInButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        logInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logInButtonActionPerformed(evt);
            }
        });

        logOutButton.setBackground(new java.awt.Color(78, 204, 163));
        logOutButton.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N
        logOutButton.setForeground(new java.awt.Color(57, 62, 70));
        logOutButton.setText("Log Out");
        logOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButtonActionPerformed(evt);
            }
        });

        createRecipeButton.setBackground(new java.awt.Color(78, 204, 163));
        createRecipeButton.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N
        createRecipeButton.setForeground(new java.awt.Color(57, 62, 70));
        createRecipeButton.setText("New Recipe");
        createRecipeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createRecipeButtonActionPerformed(evt);
            }
        });

        createMenuButton.setBackground(new java.awt.Color(78, 204, 163));
        createMenuButton.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N
        createMenuButton.setForeground(new java.awt.Color(57, 62, 70));
        createMenuButton.setText("New Menu");

        searchRecipeButton.setBackground(new java.awt.Color(78, 204, 163));
        searchRecipeButton.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N
        searchRecipeButton.setForeground(new java.awt.Color(57, 62, 70));
        searchRecipeButton.setText("Search Recipes");

        rateRecipesButton.setBackground(new java.awt.Color(78, 204, 163));
        rateRecipesButton.setFont(new java.awt.Font("Segoe UI Light", 0, 13)); // NOI18N
        rateRecipesButton.setForeground(new java.awt.Color(57, 62, 70));
        rateRecipesButton.setText("Rate Recipes");

        javax.swing.GroupLayout buttonsPanelLayout = new javax.swing.GroupLayout(buttonsPanel);
        buttonsPanel.setLayout(buttonsPanelLayout);
        buttonsPanelLayout.setHorizontalGroup(
            buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonsPanelLayout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addGroup(buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(searchRecipeButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(createMenuButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(createRecipeButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logInButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rateRecipesButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logOutButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        buttonsPanelLayout.setVerticalGroup(
            buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonsPanelLayout.createSequentialGroup()
                .addContainerGap(158, Short.MAX_VALUE)
                .addComponent(logInButton)
                .addGap(18, 18, 18)
                .addComponent(createRecipeButton)
                .addGap(18, 18, 18)
                .addComponent(createMenuButton)
                .addGap(18, 18, 18)
                .addComponent(searchRecipeButton)
                .addGap(18, 18, 18)
                .addComponent(rateRecipesButton)
                .addGap(18, 18, 18)
                .addComponent(logOutButton)
                .addGap(394, 394, 394))
        );

        jSplitPanel.setRightComponent(buttonsPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 848, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logInButtonActionPerformed
        cardLayout.show(jPanelCard, "logInCard");
        
    }//GEN-LAST:event_logInButtonActionPerformed

    private void createRecipeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createRecipeButtonActionPerformed
        cardLayout.show(jPanelCard, "recipeCard");
        
    }//GEN-LAST:event_createRecipeButtonActionPerformed

    private void priceTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceTextActionPerformed
        
    }//GEN-LAST:event_priceTextActionPerformed

    private void createRecipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createRecipeActionPerformed
        
    }//GEN-LAST:event_createRecipeActionPerformed

    private void logInUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logInUserButtonActionPerformed
        //Botones del menú si la sesión se inicia
        logInButton.setEnabled(false);
        createRecipeButton.setEnabled(true);
        createMenuButton.setEnabled(true);
        searchRecipeButton.setEnabled(true);
        rateRecipesButton.setEnabled(true);
        logOutButton.setEnabled(true);
        
        //Vamos a crear receta
        cardLayout.show(jPanelCard, "recipeCard");
    }//GEN-LAST:event_logInUserButtonActionPerformed

    private void logOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButtonActionPerformed
        //Botones del menú si la sesión se cierra
        logInButton.setEnabled(true);
        createRecipeButton.setEnabled(false);
        createMenuButton.setEnabled(false);
        searchRecipeButton.setEnabled(false);
        rateRecipesButton.setEnabled(false);
        logOutButton.setEnabled(false);
        
        //Volvemos al panel de iniciar sesión
        cardLayout.show(jPanelCard, "logInCard");
    }//GEN-LAST:event_logOutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JLabel categoriesLabel;
    private javax.swing.JList<String> categoriesList;
    private javax.swing.JScrollPane categoriesScrollPane;
    private javax.swing.JLabel cookTimeLabel;
    private javax.swing.JTextField cookTimeText;
    private javax.swing.JButton createMenuButton;
    private javax.swing.JButton createRecipe;
    private javax.swing.JButton createRecipeButton;
    private javax.swing.JLabel ingredientsLabel;
    private javax.swing.JList<String> ingredientsList;
    private javax.swing.JScrollPane ingredientsScrollPane;
    private javax.swing.JPanel jPanelCard;
    private javax.swing.JSplitPane jSplitPanel;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton logInButton;
    private javax.swing.JPanel logInPanel;
    private javax.swing.JPanel logInTittlePanel;
    private javax.swing.JLabel logInTittlePanelLabel;
    private javax.swing.JButton logInUserButton;
    private javax.swing.JButton logOutButton;
    private javax.swing.JLabel nameRecipeLabel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JTextField priceText;
    private javax.swing.JButton rateRecipesButton;
    private javax.swing.JTextField recipeNameText;
    private javax.swing.JPanel recipePanel;
    private javax.swing.JPanel recipeTittlePanel;
    private javax.swing.JLabel recipeTittlePanelLabel;
    private javax.swing.JButton resetRecipe;
    private javax.swing.JButton searchRecipeButton;
    private javax.swing.JLabel stepsLabel;
    private javax.swing.JScrollPane stepsTextArea;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTextField usernameTextArea;
    // End of variables declaration//GEN-END:variables
}
